services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy:1.4
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /var/docker/nginx/html:/usr/share/nginx/html
        - /var/docker/nginx/certs:/etc/nginx/certs
        - /var/docker/nginx/vhost:/etc/nginx/vhost.d
        - /var/docker/nginx/conf:/etc/nginx/conf.d
        - ./nginx-proxy/custom-configs/custom.conf:/etc/nginx/conf.d/custom.conf
    logging:
        options:
            max-size: "10m"
            max-file: "3"
  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
        - nginx
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/docker/nginx/acme:/etc/acme.sh
    environment:
        DEFAULT_EMAIL: ${DEFAULT_EMAIL}
  mariadb:
    image: mariadb:10.11
    ports:
      - 3306:3306
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - TZ=America/Los_Angeles 
  miniflux:
    image: miniflux/miniflux:2.0.51
    container_name: miniflux
    ports:
      - "8084:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:${FRESHRSS_MYSQL_PASSWORD}@postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${FRESHRSS_USER}
      - ADMIN_PASSWORD=${FRESHRSS_PASSWORD}
      - VIRTUAL_HOST=reader.lifeofpablo.com
      - LETSENCRYPT_HOST=reader.lifeofpablo.com
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=${FRESHRSS_MYSQL_PASSWORD}
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  vouch-proxy:
    container_name: vp-lifeofpablo
    image: quay.io/vouch/vouch-proxy:alpine-master
    ports:
      - 9090:9090
    volumes:
      - ./vouch-proxy-config:/config
    restart: always
    environment:
      VIRTUAL_HOST: auth.lifeofpablo.com
      LETSENCRYPT_HOST: auth.lifeofpablo.com
  korea:
    container_name: korea
    restart: always
    build:
      dockerfile: ./korea.lifeofpablo.com/Dockerfile  
    volumes:
      #Project root
      - ./korea.lifeofpablo.com/www/korea.lifeofpablo.com:/var/www/html
    ports:
      - "8092:80"
    environment:
      - VIRTUAL_HOST=korea.lifeofpablo.com
      - LETSENCRYPT_HOST=korea.lifeofpablo.com
  lifeofpablo-proxy:
    image: nginx:1.25.3-bookworm-perl
    container_name: lifeofpablo-proxy
    volumes:
      - ./nginx-proxy/lifeofpablo:/etc/nginx/conf.d
    ports:
      - 8110:80
    environment:
      - VIRTUAL_HOST=lifeofpablo.com
      - LETSENCRYPT_HOST=lifeofpablo.com
    depends_on:
      - lifeofpablo
      - lifeofpablo-interactives
      - lifeofpablo-linkinbio
  lifeofpablo:
    container_name: lifeofpablo
    restart: always
    build:
      dockerfile: ./lifeofpablo.com/Dockerfile  
    volumes:
      #Project root
      - ./lifeofpablo.com/www/lifeofpablo.com:/var/www/html
    environment:
      - LOP_LISTS_MUSIC_LISTENED=${LISTS_MUSIC_LISTENED}
    ports:
      - "8080:80"
  lifeofpablo-guestbook:
    container_name: lifeofpablo-guestbook
    restart: always 
    build:
      dockerfile: ./lifeofpablo-guestbook/Dockerfile  
    volumes:
      #Project root
      - ./lifeofpablo-guestbook/www/guestbook:/var/www/html
    ports:
      - "8081:80"
  lifeofpablo-linkinbio:
    container_name: lifeofpablo-linkinbio
    restart: always
    build:
      dockerfile: ./lifeofpablo-linkinbio/Dockerfile  
    volumes:
      #Project root
      - ./lifeofpablo-linkinbio/www/linkinbio:/var/www/html
    ports:
      - "8082:80"
  lifeofpablo-now:
    container_name: lifeofpablo-now
    image: ghcr.io/pmoralesgarcia/now:latest
    restart: always
    ports:
      - "8083:80"
  lifeofpablo-static:
    image: nginx:1.25.3-bookworm-perl
    container_name: lifeofpablo-static
    ports:
      - 8120:80
    volumes:
      - ./nginx-proxy/s3/static.lifeofpablo.com.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=static.lifeofpablo.com
      - LETSENCRYPT_HOST=static.lifeofpablo.com
    restart: always
  lifeofpablo-photos:
    image: nginx:1.25.3-bookworm-perl
    container_name: lifeofpablo-photos
    ports:
      - 8121:80
    volumes:
      - ./nginx-proxy/s3/photos.lifeofpablo.com.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=photos.lifeofpablo.com
      - LETSENCRYPT_HOST=photos.lifeofpablo.com
    restart: always
  lifeofpablo-nyc-climateweek:
    build:
      dockerfile: ./climateweeknyc.lifeofpablo.com/Dockerfile  
    container_name: lifeofpablo-nyc-climateweek
    ports:
      - 8122:80
    volumes:
      - ./climateweeknyc.lifeofpablo.com/www/climateweeknyc.lifeofpablo.com:/var/www/html
    environment:
      - VIRTUAL_HOST=climateweeknyc.lifeofpablo.com
      - LETSENCRYPT_HOST=climateweeknyc.lifeofpablo.com
    restart: always
  lifeofpablo-interactives:
    build:
      dockerfile: ./lifeofpablo-interactives/Dockerfile  
    container_name: lifeofpablo-interactives
    restart: always
    ports:
      - 8124:80
    volumes:
      - ./lifeofpablo-interactives/www:/var/www/html
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - '8200:80'
    restart: always
  europe24:
    container_name: europe24
    restart: always 
    build:
      dockerfile: ./europe24/Dockerfile  
    volumes:
      #Project root
      - ./europe24/www/yellow-main:/var/www/html
    ports:
      - "8125:80"
    environment:
      - VIRTUAL_HOST=eu24.lifeofpablo.com
      - LETSENCRYPT_HOST=eu24.lifeofpablo.com
  lists:
    container_name: lists
    restart: always 
    build:
      dockerfile: ./lifeofpablo-lists/Dockerfile  
    volumes:
      #Project root
      - ./lifeofpablo-lists/www:/var/www/html
    ports:
      - "8126:80"
    environment:
      - VIRTUAL_HOST=lists.lifeofpablo.com
      - LETSENCRYPT_HOST=lists.lifeofpablo.com
  1k:
    container_name: 1k
    restart: always
    build:
      dockerfile: ./1k.lifeofpablo.com/Dockerfile  
    volumes:
      #Project root
      - ./1k.lifeofpablo.com/www:/var/www/html
    ports:
      - "8127:80"
    environment:
      - VIRTUAL_HOST=1k.lifeofpablo.com
      - LETSENCRYPT_HOST=1k.lifeofpablo.com
  ghost:
    build: personivebecome
    cap_add:
      - CAP_SYS_NICE
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mariadb
    environment:
      url: https://personivebecome.com
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: ghost
      database__connection__password: ${GHOST_MYSQL_PASSWORD}
      database__connection__database: ghost
      mail__service: Mailgun
      mail__transport: SMTP
      mail__options__host: ${GHOST_SMTP_RELAY}
      mail__options__port: ${GHOST_SMTP_PORT}
      mail__options__auth__user: ${GHOST_SMTP_USER}
      mail__options__auth__pass: ${GHOST_SMTP_PASSWORD}
      APP_TRUSTED_PROXIES: REMOTE_ADDR
      mail__from: "Person I've Become Podcast"
      VIRTUAL_HOST: personivebecome.com
      LETSENCRYPT_HOST: personivebecome.com
    volumes:
      - ./ghost/content:/var/lib/ghost/content
  yourls:
    image: yourls:1.9.2
    container_name: yourls
    restart: always
    ports:
      - 8201:80
    environment:
      YOURLS_DB_HOST: mariadb
      YOURLS_DB_USER: ${YOURLS_DB_USER}
      YOURLS_DB_PASS: ${YOURLS_DB_PASS}
      YOURLS_SITE: https://pabs.lol
      YOURLS_USER: ${YOURLS_USER}
      YOURLS_PASS: ${YOURLS_PASS}
      VIRTUAL_HOST: pabs.lol
      LETSENCRYPT_HOST: pabs.lol
    volumes:
      - ./yourls/plugins:/var/www/html/user/plugins
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VIRTUAL_HOST=grocy.lifeofpablo.com
      - LETSENCRYPT_HOST=grocy.lifeofpablo.com
    volumes:
      - ./grocy/config:/config
    ports:
      - 9283:80
    restart: unless-stopped
  owntracks-recorder:
    container_name: owntracks-recorder
    image: owntracks/recorder
    ports:
      - 9285:8083
    environment:
      - OTR_PORT=0 # disables MQTT
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./owntracks-recorder/config:/config
      - ./owntracks-recorder/store:/store
    restart: unless-stopped
  owntracks-frontend:
    container_name: owntracks-frontend
    image: owntracks/frontend
    ports:
      - 9287:80
    volumes:
      - ./owntracks-frontend/config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=owntracks-recorder
      - SERVER_PORT=8083
    restart: unless-stopped

volumes:
 mariadb:
 miniflux-db:
