services:
  #reverse-proxy:
   # container_name: reverse-proxy
   # hostname: reverse-proxy
   # image: nginx
   # ports:
   #   - 80:80
   #   - 443:443
   # volumes:
   #   - /home/pablo/pabsnet/nginx-configs:/etc/nginx
  vouch-proxy:
    container_name: vp-lifeofpablo
    image: quay.io/vouch/vouch-proxy
    ports:
      - 9092:9090
    environment:
      - VOUCH_DOMAINS=${VOUCH_DOMAIN}
      - VOUCH_ALLOWALLUSERS=${VOUCH_ALLOWALLUSERS}
      - VOUCH_COOKIE_SECURE=${VOUCH_COOKIE_SECURE}
      - VOUCH_PUBLIC_ACCESS=${VOUCH_PUBLIC_ACCESS}
      - OAUTH_PROVIDER=${VOUCH_OAUTH_PROVIDER}
      - OAUTH_CLIENT_ID=${VOUCH_OAUTH_CLIENT_ID}
      - OAUTH_AUTH_URL=${VOUCH_OAUTH_AUTH_URL}
      - OAUTH_CALLBACK_URL=${VOUCH_OAUTH_CALLBACK_URL}
      
  bludit:
    container_name: pablospicassos
    image: bludit/docker:3.13.1
    ports:
      - 8098:80
    volumes:
      - bludit:/home/pablo/bludit:/usr/share/nginx/html/bl-content
    restart: always
  lifeofpablo-now:
    image: ghcr.io/pmoralesgarcia/now:latest
    ports:
      - 8086:80
    restart: always
  mariadb:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306
  freshrss:
    depends_on:
      - mariadb
    image: freshrss/freshrss:latest
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions 
    ports:
      - 8085:80
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      FRESHRSS_INSTALL: |-
        --api_enabled
        --db-base freshrss
        --db-host mariadb
        --db-password ${MYSQL_ROOT_PASSWORD}
        --db-type mysql 
        --db-user freshrss 
        --default_user ${FRESHRSS_USER}
        --language en
      FRESHRSS_USER: |-
        --api_password ${FRESHRSS_API_PASSWORD}
        --email ${FRESHRSS_EMAIL}
        --language en
        --password ${FRESHRSS_PASSWORD}
        --user ${FRESHRSS_USER}

volumes:
 bludit:
 db_data:
 data: 
 extensions:
