services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /var/docker/nginx/html:/usr/share/nginx/html
        - /var/docker/nginx/certs:/etc/nginx/certs
        - /var/docker/nginx/vhost:/etc/nginx/vhost.d
        - /var/docker/nginx/conf:/etc/nginx/conf.d
    logging:
        options:
            max-size: "10m"
            max-file: "3"
  lifeofpablo:
    container_name: lifeofpablo-com
    expose:
      - 80
    build:
      context: .
      dockerfile: ./lifeofpablo.com/Dockerfile
    volumes:
      - ./lifeofpablo.com/www/lifeofpablo.com:/var/www/lifeofpablo.com
    environment:
      VIRTUAL_HOST: lifeofpablo.com
  bludit:
    container_name: pablospicassos
    image: bludit/docker:3.13.1
    ports:
      - 8098:80
    volumes:
      - bludit:/home/pablo/bludit:/usr/share/nginx/html/bl-content
    restart: always
  lifeofpablo-now:
    image: ghcr.io/pmoralesgarcia/now:latest
    ports:
      - 8086:80
    restart: always
  mariadb:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./matomo/db.env
  matomo:
    image: matomo
    restart: always
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./matomo/db.env
  matomo-nginx:
    container_name: matomo-nginx
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo/matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    environment:
      VIRTUAL_HOST: matomo.lifeofpablo.com
    ports:
      - 8210:80
    depends_on:
      - matomo
  freshrss:
    depends_on:
      - mariadb
      - vouch-proxy
    image: freshrss/freshrss
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    ports:
      - 8085:80
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      TRUSTED_PROXY: "0.0.0.0/0"
      FRESHRSS_INSTALL: |-
        --api_enabled
        --db-base freshrss
        --db-host mariadb
        --db-password ${FRESHRSS_MYSQL_PASSWORD}
        --db-type mysql
        --db-user ${FRESHRSS_MYSQL_USER}
        --default_user ${FRESHRSS_USER}
        --language en
      FRESHRSS_USER: |-
        --api_password ${FRESHRSS_API_PASSWORD}
        --email ${FRESHRSS_EMAIL}
        --language en
        --password ${FRESHRSS_PASSWORD}
        --user ${FRESHRSS_USER}
  vp-proxy-freshrss:
    image: nginx:latest
    container_name: vp-proxy-freshrss
    environment:
      VIRTUAL_HOST: reader.lifeofpablo.com
    #  LETSENCRYPT_HOST: reader.lifeofpablo.com
    volumes:
      - ./nginx-proxy/freshrss:/etc/nginx/conf.d
    ports:
      - 8112:80
  vouch-proxy:
    container_name: vp-lifeofpablo
    image: quay.io/vouch/vouch-proxy
    ports:
      - 9090:9090
    volumes:
      - ./vouch-proxy-config:/config
    restart: always
    environment:
      VIRTUAL_HOST: auth.lifeofpablo.com
  shlink:
    container_name: pabs-lol
    image: shlinkio/shlink:3.6.3-openswoole
    ports:
      - 8110:8080
    environment:
      - DEFAULT_DOMAIN=pabs.lol
      - DB_DRIVER=mysql
      - DB_USER=${SHLINK_MYSQL_USER}
      - DB_PASSWORD=${SHLINK_MYSQL_PASSWORD}
      - DB_HOST=mariadb
      - INITIAL_API_KEY=${SHLINK_API_KEY}
    restart: always
    depends_on:
      - mariadb
  shlink-web-client:
    container_name: pabs-lol-web-client
    image: shlinkio/shlink-web-client:3.10
    ports:
      - 8111:80
    environment:
      - SHLINK_SERVER_URL=https://pabs.lol
      - SHLINK_SERVER_API_KEY=${SHLINK_API_KEY}
      - SHLINK_SERVER_NAME=Pabs
    restart: always
  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - 8209:80
volumes:
 bludit:
 mariadb:
 matomo:
 freshrss_data:
 freshrss_extensions: