services:
  #reverse-proxy:
   # container_name: reverse-proxy
   # hostname: reverse-proxy
   # image: nginx
   # ports:
   #   - 80:80
   #   - 443:443
   # volumes:
   #   - /home/pablo/pabsnet/nginx-configs:/etc/nginx
  bludit:
    container_name: pablospicassos
    image: bludit/docker:3.13.1
    ports:
      - 8098:80
    volumes:
      - bludit:/home/pablo/bludit:/usr/share/nginx/html/bl-content
    restart: always
  lifeofpablo-now:
    image: ghcr.io/pmoralesgarcia/now:latest
    ports:
      - 8086:80
    restart: always
  convos:
    image: convos/convos:v7.15
    ports:
      - 8092:3000
    volumes:
      - convos:/home/pablo/convos/data
    restart: always
  mariadb:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306
  freshrss:
    depends_on:
      - mariadb
    image: freshrss/freshrss:latest
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions 
    ports:
      - 8085:80
    restart: always
    logging:
      options:
        max-size: 10m
    environment:
      FRESHRSS_INSTALL: |-
        --api_enabled
        --db-base freshrss
        --db-host mariadb
        --db-password ${MYSQL_PASSWORD}
        --db-type mysql 
        --db-user freshrss 
        --default_user ${FRESHRSS_USER}
        --language en
      FRESHRSS_USER: |-
        --api_password ${FRESHRSS_API_PASSWORD}
        --email ${FRESHRSS_EMAIL}
        --language en
        --password ${FRESHRSS_PASSWORD}
        --user ${FRESHRSS_USER}
  shlink:
    container_name: pabs-lol
    image: shlinkio/shlink:3.6.3-openswoole
    ports:
      - 8110:8080
    environment:
      - DEFAULT_DOMAIN=pabs.lol
      - DB_DRIVER=mysql
      - DB_USER=${SHLINK_MYSQL_USER}
      - DB_PASSWORD=${SHLINK_MYSQL_PASSWORD}
      - DB_HOST=shlink-db
      - INITIAL_API_KEY=${SHLINK_API_KEY}
    restart: always
    depends_on:
      - mariadb
  shlink-web-client:
    container_name: pabs-lol-web-client
    image: shlinkio/shlink-web-client:3.10
    ports:
      - 8111:80
    environment:
      - SHLINK_SERVER_URL=https://pabs.lol
      - SHLINK_SERVER_API_KEY=${SHLINK_API_KEY}
      - SHLINK_SERVER_NAME=Pabs
    restart: always
volumes:
 bludit:
 convos:
 db_data:
 data: 
 extensions:
