- service: httpbin
  default:
    from: httpbin.sso.lifeofpablo.com
    to: http://httpbin:8080

- service: hello-world
  default:
    from: hello-world.sso.lifeofpablo.com
    to: http://hello-world/


- service: it-tools
  default:
    from: it-tools.sso.lifeofpablo.com
    to: http://it-tools/
      

- service: jetlogs
  default:
    from: jetlogs.sso.lifeofpablo.com
    to: http://jetlog:3000


- service: dozzle 
  default:
    from: dozzle.sso.lifeofpablo.com
    to: http://dozzle