- service: httpbin
  default:
    from: https://httpbin.sso.lifeofpablo.com
    to: http://httpbin:8200

- service: owntracks-frontend
  default:
    from: https://find.sso.lifeofpablo.com
    to: http://owntracks-frontend/
    skip_auth_regex:
        - ^\/pub\/$



