version: "3"
services:
  mariadb:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./matomo/db.env
  matomo:
    image: matomo:fpm-alpine
    restart: always
    links:
      - mariadb
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./matomo/db.env
  matomo-nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo/matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - 8210:80
volumes:
  mariadb:
  matomo:
