name: Deploy docker compose
on:
  workflow_dispatch:
  push:
    paths:
      - 'docker-compose.yml'
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
       # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          USERNAME: op://pablo/pabsnet2/username
          PRIVATE_SSH_KEY: op://pablo/pabsnet2/private key
          SERVER_HOST: op://pablo/pabsnet2/host
          MYSQL_ROOT_PASSWORD: op://pablo/mariadb-docker/root_password
          FRESHRSS_MYSQL_USER: op://pablo/freshrss-docker/mysql_user
          FRESHRSS_MYSQL_PASSWORD: op://pablo/freshrss-docker/mysql_password
          FRESHRSS_USER: op://pablo/freshrss-docker/freshrss_user
          FRESHRSS_EMAIL: op://pablo/freshrss-docker/freshrss_email
          FRESHRSS_PASSWORD: op://pablo/freshrss-docker/freshrss_password
          FRESHRSS_API_PASSWORD: op://pablo/freshrss-docker/FRESHRSS_API_PASSWORD
          DEFAULT_EMAIL: op://pablo/default_email/email
          SHLINK_MYSQL_PASSWORD: op://pablo/shlink/SHLINK_MYSQL_PASSWORD
          SHLINK_MYSQL_USER: op://pablo/shlink/SHLINK_MYSQL_USER
          SHLINK_API_KEY: op://pablo/shlink/SHLINK_API_KEY
          VOUCH_ALLOWALLUSERS: op://pablo/vp-lifeofpablo/VOUCH_ALLOWALLUSERS
          VOUCH_DOMAIN: op://pablo/vp-lifeofpablo/VOUCH_DOMAIN
          VOUCH_COOKIE_SECURE: op://pablo/vp-lifeofpablo/VOUCH_COOKIE_SECURE
          VOUCH_PUBLIC_ACCESS: op://pablo/vp-lifeofpablo/VOUCH_PUBLIC_ACCESS
          VOUCH_OAUTH_CLIENT_ID: op://pablo/vp-lifeofpablo/VOUCH_OAUTH_CLIENT_ID
          VOUCH_OAUTH_AUTH_URL: op://pablo/vp-lifeofpablo/VOUCH_OAUTH_AUTH_URL
          VOUCH_OAUTH_CALLBACK_URL: op://pablo/vp-lifeofpablo/VOUCH_OAUTH_CALLBACK_URL
          MATOMO_MYSQL_USER: op://pablo/matomo/username
          MATOMO_MYSQL_DATABASE: op://pablo/matomo/database
          MATOMO_MYSQL_PASSWORD: op://pablo/matomo/password
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.op-load-secret.outputs.SERVER_HOST }}
          username: ${{ steps.op-load-secret.outputs.USERNAME }}
          key: ${{ steps.op-load-secret.outputs.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd ~/pabsnet
            git pull
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            docker compose build --no-cache
            FRESHRSS_MYSQL_USER=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_USER }} \
            FRESHRSS_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_PASSWORD }} \
            MYSQL_ROOT_PASSWORD=${{ steps.op-load-secret.outputs.MYSQL_ROOT_PASSWORD }} \
            FRESHRSS_USER=${{ steps.op-load-secret.outputs.FRESHRSS_USER }} \
            FRESHRSS_EMAIL=${{ steps.op-load-secret.outputs.FRESHRSS_EMAIL }} \
            FRESHRSS_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_PASSWORD }} \
            FRESHRSS_API_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_API_PASSWORD }} \
            DEFAULT_EMAIL=${{ steps.op-load-secret.outputs.DEFAULT_EMAIL }} \
            SHLINK_MYSQL_USER=${{ steps.op-load-secret.outputs.SHLINK_MYSQL_USER }} \
            SHLINK_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.SHLINK_MYSQL_PASSWORD }} \
            SHLINK_API_KEY=${{ steps.op-load-secret.outputs.SHLINK_API_KEY }} \
            VOUCH_ALLOW_ALL_USERS=${{ steps.op-load-secret.outputs.VOUCH_ALLOW_ALL_USERS }} \
            VOUCH_DOMAIN=${{ steps.op-load-secret.outputs.VOUCH_DOMAIN }} \
            VOUCH_COOKIE_SECURE=${{ steps.op-load-secret.outputs.VOUCH_COOKIE_SECURE }} \
            VOUCH_PUBLIC_ACCESS=${{ steps.op-load-secret.outputs.VOUCH_PUBLIC_ACCESS }} \
            VOUCH_OAUTH_CLIENT_ID=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_CLIENT_ID }} \
            VOUCH_OAUTH_AUTH_URL=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_AUTH_URL }} \
            VOUCH_OAUTH_CALLBACK_URL=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_CALLBACK_URL }} \
            VOUCH_OAUTH_PROVIDER=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_PROVIDER }} \
            MATOMO_MYSQL_USER=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_USER }} \
            MATOMO_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_PASSWORD }} \
            MATOMO_MYSQL_DATABASE=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            docker compose down --remove-orphans
            FRESHRSS_MYSQL_USER=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_USER }} \
            FRESHRSS_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_PASSWORD }} \
            MYSQL_ROOT_PASSWORD=${{ steps.op-load-secret.outputs.MYSQL_ROOT_PASSWORD }} \
            FRESHRSS_USER=${{ steps.op-load-secret.outputs.FRESHRSS_USER }} \
            FRESHRSS_EMAIL=${{ steps.op-load-secret.outputs.FRESHRSS_EMAIL }} \
            FRESHRSS_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_PASSWORD }} \
            FRESHRSS_API_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_API_PASSWORD }} \
            DEFAULT_EMAIL=${{ steps.op-load-secret.outputs.DEFAULT_EMAIL }} \
            SHLINK_MYSQL_USER=${{ steps.op-load-secret.outputs.SHLINK_MYSQL_USER }} \
            SHLINK_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.SHLINK_MYSQL_PASSWORD }} \
            SHLINK_API_KEY=${{ steps.op-load-secret.outputs.SHLINK_API_KEY }} \
            VOUCH_ALLOW_ALL_USERS=${{ steps.op-load-secret.outputs.VOUCH_ALLOW_ALL_USERS }} \
            VOUCH_DOMAIN=${{ steps.op-load-secret.outputs.VOUCH_DOMAIN }} \
            VOUCH_COOKIE_SECURE=${{ steps.op-load-secret.outputs.VOUCH_COOKIE_SECURE }} \
            VOUCH_PUBLIC_ACCESS=${{ steps.op-load-secret.outputs.VOUCH_PUBLIC_ACCESS }} \
            VOUCH_OAUTH_CLIENT_ID=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_CLIENT_ID }} \
            VOUCH_OAUTH_AUTH_URL=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_AUTH_URL }} \
            VOUCH_OAUTH_CALLBACK_URL=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_CALLBACK_URL }} \
            VOUCH_OAUTH_PROVIDER=${{ steps.op-load-secret.outputs.VOUCH_OAUTH_PROVIDER }} \
            MATOMO_MYSQL_USER=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_USER }} \
            MATOMO_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            MATOMO_MYSQL_DATABASE=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            docker compose up --detach
