name: Deploy docker compose
on:
  workflow_dispatch:
  push:
    paths:
      - 'docker-compose.yml'
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
       # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          API_DB_HOST: op://pablo/lists-pabsnet2/server
          API_DB_PASS: op://pablo/lists-pabsnet2/password
          API_DB_USER: op://pablo/lists-pabsnet2/username
          API_DB: op://pablo/lists-pabsnet2/database
          USERNAME: op://pablo/pabsnet2/username
          PRIVATE_SSH_KEY: op://pablo/pabsnet2/private key
          SERVER_HOST: op://pablo/pabsnet2/host
          MYSQL_ROOT_PASSWORD: op://pablo/mariadb-docker/root_password
          FRESHRSS_MYSQL_USER: op://pablo/freshrss-docker/mysql_user
          FRESHRSS_MYSQL_PASSWORD: op://pablo/freshrss-docker/mysql_password
          FRESHRSS_USER: op://pablo/freshrss-docker/freshrss_user
          FRESHRSS_EMAIL: op://pablo/freshrss-docker/freshrss_email
          FRESHRSS_PASSWORD: op://pablo/freshrss-docker/freshrss_password
          FRESHRSS_API_PASSWORD: op://pablo/freshrss-docker/FRESHRSS_API_PASSWORD
          DEFAULT_EMAIL: op://pablo/default_email/email
          YOURLS_DB_USER: op://pablo/YOURLS/YOURLS_DB_USER
          YOURLS_DB_PASS: op://pablo/YOURLS/YOURLS_DB_PASS
          YOURLS_USER: op://pablo/YOURLS/username
          YOURLS_PASS: op://pablo/YOURLS/password
          YOURLS_API: op://pablo/YOURLS/YOURLS_API
          MATOMO_MYSQL_USER: op://pablo/matomo/username
          MATOMO_MYSQL_DATABASE: op://pablo/matomo/database
          MATOMO_MYSQL_PASSWORD: op://pablo/matomo/password
          GHOST_MYSQL_PASSWORD: op://pablo/ghost-pabsnet/password
          GHOST_SMTP_RELAY: op://pablo/ghost-pabsnet/smtp_relay
          GHOST_SMTP_PORT: op://pablo/ghost-pabsnet/smtp_port
          GHOST_SMTP_USER: op://pablo/ghost-pabsnet/email
          GHOST_SMTP_PASSWORD: op://pablo/ghost-pabsnet/app_password
          N8N_DB_PORT: op://pablo/n8n-docker/N8N_DB_PORT
          N8N_DB: op://pablo/n8n-docker/N8N_DB
          N8N_USER: op://pablo/n8n-docker/N8N_PG_USER
          N8N_PW: op://pablo/n8n-docker/N8N_PG_PW
          N8N_PG_USER: op://pablo/n8n-docker/N8N_PG_USER
          N8N_PG_PW: op://pablo/n8n-docker/N8N_PG_PW
          N8N_PG_DB: op://pablo/n8n-docker/N8N_PG_DB
          N8N_PG_USER1: op://pablo/n8n-docker/N8N_PG_USER
          N8N_PG_DB1: op://pablo/n8n-docker/N8N_PG_DB
          N8N_PG_NON_ROOT_USER: op://pablo/n8n-docker/N8N_PG_NON_ROOT_USER
          N8N_PG_NON_ROOT_PW: op://pablo/n8n-docker/N8N_PG_NON_ROOT_PW 
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.op-load-secret.outputs.SERVER_HOST }}
          username: ${{ steps.op-load-secret.outputs.USERNAME }}
          key: ${{ steps.op-load-secret.outputs.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd ~/pabsnet
            git pull
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            API_DB_HOST=${{ steps.op-load-secret.outputs.API_DB_HOST }} \
            API_DB_USER=${{ steps.op-load-secret.outputs.API_DB_USER }} \
            API_DB_PASS=${{ steps.op-load-secret.outputs.API_DB_PASS }} \
            API_DB=${{ steps.op-load-secret.outputs.API_DB }} \
            FRESHRSS_MYSQL_USER=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_USER }} \
            FRESHRSS_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_PASSWORD }} \
            MYSQL_ROOT_PASSWORD=${{ steps.op-load-secret.outputs.MYSQL_ROOT_PASSWORD }} \
            FRESHRSS_USER=${{ steps.op-load-secret.outputs.FRESHRSS_USER }} \
            FRESHRSS_EMAIL=${{ steps.op-load-secret.outputs.FRESHRSS_EMAIL }} \
            FRESHRSS_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_PASSWORD }} \
            FRESHRSS_API_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_API_PASSWORD }} \
            DEFAULT_EMAIL=${{ steps.op-load-secret.outputs.DEFAULT_EMAIL }} \
            YOURLS_DB_USER=${{ steps.op-load-secret.outputs.YOURLS_DB_USER }} \
            YOURLS_DB_PASS=${{ steps.op-load-secret.outputs.YOURLS_DB_PASS }} \
            YOURLS_USER=${{ steps.op-load-secret.outputs.YOURLS_USER }} \
            YOURLS_PASS=${{ steps.op-load-secret.outputs.YOURLS_PASS }} \
            YOURLS_API=${{ steps.op-load-secret.outputs.YOURLS_API }} \
            MATOMO_MYSQL_USER=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_USER }} \
            MATOMO_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_PASSWORD }} \
            MATOMO_MYSQL_DATABASE=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            GHOST_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.GHOST_MYSQL_PASSWORD }} \
            GHOST_SMTP_RELAY=${{ steps.op-load-secret.outputs.GHOST_SMTP_RELAY }} \
            GHOST_SMTP_PORT=${{ steps.op-load-secret.outputs.GHOST_SMTP_PORT }} \
            GHOST_SMTP_USER=${{ steps.op-load-secret.outputs.GHOST_SMTP_USER }} \
            GHOST_SMTP_PASSWORD=${{ steps.op-load-secret.outputs.GHOST_SMTP_PASSWORD }} \
            N8N_DB_PORT=${{ steps.op-load-secret.outputs.N8N_DB_PORT }} \
            N8N_DB=${{ steps.op-load-secret.outputs.N8N_DB }} \
            N8N_USER=${{ steps.op-load-secret.outputs.N8N_USER }} \
            N8N_PW=${{ steps.op-load-secret.outputs.N8N_PW }} \
            N8N_PG_USER=${{ steps.op-load-secret.outputs.N8N_PG_USER }} \
            N8N_PG_PW=${{ steps.op-load-secret.outputs.N8N_PG_PW }} \
            N8N_PG_DB=${{ steps.op-load-secret.outputs.N8N_PG_DB }} \
            N8N_PG_NON_ROOT_USER=${{ steps.op-load-secret.outputs.N8N_PG_NON_ROOT_USER }} \
            N8N_PG_NON_ROOT_PW=${{ steps.op-load-secret.outputs.N8N_PG_NON_ROOT_PW }} \
            docker compose down
            API_DB_HOST=${{ steps.op-load-secret.outputs.API_DB_HOST }} \
            API_DB_USER=${{ steps.op-load-secret.outputs.API_DB_USER }} \
            API_DB_PASS=${{ steps.op-load-secret.outputs.API_DB_PASS }} \
            API_DB=${{ steps.op-load-secret.outputs.API_DB }} \
            FRESHRSS_MYSQL_USER=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_USER }} \
            FRESHRSS_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_MYSQL_PASSWORD }} \
            MYSQL_ROOT_PASSWORD=${{ steps.op-load-secret.outputs.MYSQL_ROOT_PASSWORD }} \
            FRESHRSS_USER=${{ steps.op-load-secret.outputs.FRESHRSS_USER }} \
            FRESHRSS_EMAIL=${{ steps.op-load-secret.outputs.FRESHRSS_EMAIL }} \
            FRESHRSS_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_PASSWORD }} \
            FRESHRSS_API_PASSWORD=${{ steps.op-load-secret.outputs.FRESHRSS_API_PASSWORD }} \
            DEFAULT_EMAIL=${{ steps.op-load-secret.outputs.DEFAULT_EMAIL }} \
            YOURLS_DB_USER=${{ steps.op-load-secret.outputs.YOURLS_DB_USER }} \
            YOURLS_DB_PASS=${{ steps.op-load-secret.outputs.YOURLS_DB_PASS }} \
            YOURLS_USER=${{ steps.op-load-secret.outputs.YOURLS_USER }} \
            YOURLS_PASS=${{ steps.op-load-secret.outputs.YOURLS_PASS }} \
            YOURLS_API=${{ steps.op-load-secret.outputs.YOURLS_API }} \
            MATOMO_MYSQL_USER=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_USER }} \
            MATOMO_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            MATOMO_MYSQL_DATABASE=${{ steps.op-load-secret.outputs.MATOMO_MYSQL_DATABASE }} \
            GHOST_MYSQL_PASSWORD=${{ steps.op-load-secret.outputs.GHOST_MYSQL_PASSWORD }} \
            GHOST_SMTP_RELAY=${{ steps.op-load-secret.outputs.GHOST_SMTP_RELAY }} \
            GHOST_SMTP_PORT=${{ steps.op-load-secret.outputs.GHOST_SMTP_PORT }} \
            GHOST_SMTP_USER=${{ steps.op-load-secret.outputs.GHOST_SMTP_USER }} \
            GHOST_SMTP_PASSWORD=${{ steps.op-load-secret.outputs.GHOST_SMTP_PASSWORD }} \
            N8N_DB_PORT=${{ steps.op-load-secret.outputs.N8N_DB_PORT }} \
            N8N_DB=${{ steps.op-load-secret.outputs.N8N_DB }} \
            N8N_USER=${{ steps.op-load-secret.outputs.N8N_USER }} \
            N8N_PW=${{ steps.op-load-secret.outputs.N8N_PW }} \
            N8N_PG_USER=${{ steps.op-load-secret.outputs.N8N_PG_USER }} \
            N8N_PG_PW=${{ steps.op-load-secret.outputs.N8N_PG_PW }} \
            N8N_PG_DB=${{ steps.op-load-secret.outputs.N8N_PG_DB }} \
            N8N_PG_NON_ROOT_USER=${{ steps.op-load-secret.outputs.N8N_PG_NON_ROOT_USER }} \
            N8N_PG_NON_ROOT_PW=${{ steps.op-load-secret.outputs.N8N_PG_NON_ROOT_PW }} \
            docker compose up --detach