name: Publish login.lifeofpablo.com Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: login.lifeofpablo.com
        
    steps:          
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
<<<<<<< HEAD
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./login.lifeofpablo.com
          push: true
          tags: |
            ghcr.io/pmoralesgarcia/login:latest
=======
                    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ steps.op-load-secret.outputs.SERVER_HOST }}
        username: ${{ steps.op-load-secret.outputs.USERNAME }}
        key: ${{ steps.op-load-secret.outputs.PRIVATE_SSH_KEY }}
        port: 22
        script: |
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          cd ~/pabsnet
          git pull
          docker rm $(docker stop $(docker ps -a -q --filter ancestor=now))
          cd ~/pabsnet/login.lifeofpablo.com
          docker build . -t selfauth-login:latest
          docker run -d -p 8081:80 -v ./www/login.lifeofpablo.com:/var/www/login.lifeofpablo.com selfauth-login        
  
>>>>>>> parent of a961f70 (Update login.lifeofpablo.com.yml)
